version: '3.8'
name: arches_her6-2
services:
    aher:
      container_name: aher6-2
      image: fargeo/aher6-2
      build:
        context: ..
        dockerfile: arches_her/Dockerfile
      command: run_arches
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/arches_her
      env_file:
        - ./docker/env_file.env
      ports:
        - 8003:8000
      stdin_open: true
      tty: true

networks:
  default:
    external: true
    name: arches6-2-dev

volumes:
    arches-log-aher6-2:
    arches-static-aher6-2:
