# Generated by Django 2.2.24 on 2024-11-29 14:14

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('arches_her', '0001_initial'), ('arches_her', '0002_heritageapilog_resources'), ('arches_her', '0003_auto_20241031_0434'), ('arches_her', '0004_auto_20241031_1033'), ('arches_her', '0005_auto_20241031_1037')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageApiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('batch_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('start', models.DateTimeField(default=datetime.datetime.now)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('run_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('totals', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('messages', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('exceptions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Heritage API Log',
                'verbose_name_plural': 'Heritage API Logs',
                'db_table': 'hapi_log',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='heritageapilog',
            index=models.Index(fields=['batch_id'], name='hapi_log_batch_i_28b552_idx'),
        ),
        migrations.AddField(
            model_name='heritageapilog',
            name='resources',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HeritageApiExclusion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_id', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Heritage API Exclusion',
                'verbose_name_plural': 'Heritage API Exclusions',
                'db_table': 'hapi_exclusion',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='heritageapiexclusion',
            index=models.Index(fields=['resource_id'], name='hapi_exclus_resourc_fc126a_idx'),
        ),
        migrations.AlterField(
            model_name='heritageapiexclusion',
            name='resource_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='heritageapiexclusion',
            name='resource_id',
            field=models.UUIDField(unique=True),
        ),
    ]
