# Generated by Django 2.2.24 on 2024-10-30 07:07

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageApiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('batch_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('start', models.DateTimeField(default=datetime.datetime.now)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('run_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('totals', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('messages', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('exceptions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Heritage API Log',
                'verbose_name_plural': 'Heritage API Logs',
                'db_table': 'hapi_log',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='heritageapilog',
            index=models.Index(fields=['batch_id'], name='hapi_log_batch_i_28b552_idx'),
        ),
    ]
