# Generated by Django 2.2.24 on 2024-10-30 11:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageapilog',
            name='resources',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
