# Generated by Django 2.2.24 on 2025-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0001_initial_squashed_0005_auto_20241031_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageApiInclusion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_id', models.UUIDField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Heritage API Inclusion',
                'verbose_name_plural': 'Heritage API Inclusions',
                'db_table': 'hapi_inclusion',
                'managed': True,
            },
        ),
        migrations.RemoveIndex(
            model_name='heritageapiexclusion',
            name='hapi_exclus_resourc_fc126a_idx',
        ),
        migrations.AddIndex(
            model_name='heritageapiexclusion',
            index=models.Index(fields=['resource_id'], name='hapi_exclus_resourc_fc126a_idx'),
        ),
        migrations.AddIndex(
            model_name='heritageapiinclusion',
            index=models.Index(fields=['resource_id'], name='hapi_inclus_resourc_1989a7_idx'),
        ),
    ]
