# Generated by Django 2.2.24 on 2025-01-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0002_auto_20250124_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritageapiinclusion',
            name='resource_id',
            field=models.UUIDField(unique=True),
        ),
    ]
