# Generated by Django 2.2.24 on 2024-10-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0002_heritageapilog_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageApiExclusion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_id', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Heritage API Exclusion',
                'verbose_name_plural': 'Heritage API Exclusions',
                'db_table': 'hapi_exclusion',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='heritageapiexclusion',
            index=models.Index(fields=['resource_id'], name='hapi_exclus_resourc_fc126a_idx'),
        ),
    ]
