# Generated by Django 2.2.24 on 2024-10-31 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0003_auto_20241031_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritageapiexclusion',
            name='resource_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
