# Generated by Django 2.2.24 on 2025-01-27 16:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0003_auto_20250124_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageapilog',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='heritageapilog',
            index=models.Index(fields=['start'], name='hapi_log_start_63eb5c_idx'),
        ),
    ]
