# Generated by Django 2.2.24 on 2025-02-03 15:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0004_auto_20250127_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageApiData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('hapi_log_id', models.UUIDField()),
                ('batch_id', models.PositiveIntegerField()),
                ('part', models.PositiveIntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='heritageapilog',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
