# Generated by Django 2.2.24 on 2024-10-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0004_auto_20241031_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritageapiexclusion',
            name='resource_id',
            field=models.UUIDField(unique=True),
        ),
    ]
