# Generated by Django 2.2.24 on 2025-02-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0005_auto_20250203_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heritageapilog',
            name='data',
        ),
    ]
