# Generated by Django 2.2.24 on 2025-02-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0006_remove_heritageapilog_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heritageapidata',
            options={'managed': True, 'verbose_name': 'Heritage API Data', 'verbose_name_plural': 'Heritage API Data'},
        ),
        migrations.AddIndex(
            model_name='heritageapidata',
            index=models.Index(fields=['batch_id', 'part'], name='hapi_data_batch_i_e31e49_idx'),
        ),
        migrations.AlterModelTable(
            name='heritageapidata',
            table='hapi_data',
        ),
    ]
