# Generated by Django 2.2.24 on 2025-02-04 11:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0007_auto_20250203_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageapidata',
            name='validation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
