# Generated by Django 2.2.24 on 2025-04-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0008_heritageapidata_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritageapilog',
            name='batch_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
