# Generated by Django 2.2.24 on 2025-04-24 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0009_auto_20250424_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageapidata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
