# Generated by Django 2.2.24 on 2026-06-25 08:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0010_heritageapidata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageApiProtectedStatus',
            fields=[
                ('source_concept', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('heritage_gateway_concept', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Heritage API Protected Status',
                'verbose_name_plural': 'Heritage API Protected Statuses',
                'db_table': 'hapi_protected_status',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='heritageapidata',
            name='submission_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heritageapidata',
            name='batch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heritageapidata',
            name='part',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='heritageapidata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='heritageapilog',
            name='batch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heritageapilog',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
