# Generated by Django 2.2.24 on 2026-07-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arches_her', '0012_heritageapiconceptmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeritageApiProtectedStatus',
        ),
    ]
